#!/bin/bash

ARCHIVE_DIR='/media/removable/sd/to archive'


if [ ! -d "$ARCHIVE_DIR" ]; then
    echo "Error! $ARCHIVE_DIR not found!" 1>&2
    exit 1
fi

rsync --dry-run --remove-source-files --exclude "*/node_modules/" -Pr "$1" "$ARCHIVE_DIR"/
