#!/bin/bash

DEFAULT_DEVICE="bdwrt5677"

help () {
cat << 'EOF'
audio [ cras | jack | help ]

audio cras : pipes ALSA through CRAS

audio jack [ device ]: pipes ALSA through JACK

Get list of devices with `cat /proc/asound/cards`
To route JACK through supercollider, edit ~/.asoundrc manually,
replacing "rawjack" with "supercollider in "pcm.!default"
EOF
}


CRAS="$(cat << EOF
# ALSA to CRAS
pcm.!default { 
    type cras
}

ctl.!default { 
    type cras
}
EOF
)"


JACK="$(cat << EOF
# ALSA to JACK

pcm.rawjack {
    type jack
    playback_ports {
        0 system:playback_1
        1 system:playback_2
    }
    capture_ports {
        0 system:capture_1
        1 system:capture_2
    }
}

pcm.supercollider{
    type jack
    playback_ports {
        0 SuperCollider:in_1
        1 SuperCollider:in_2
    }
    capture_ports {
        0 SuperCollider:out_1
        1 SuperCollider:out_2
    }
}

# We still want control over our backend device
ctl.!default { 
    type hw
    card "_DEVICE_"
}

pcm.!default {
    type plug
    slave { pcm "rawjack"  }
}

EOF
)"


case "$1" in
    "cras") 
        echo "Start CRAS:"
        sudo start cras
        echo "$CRAS" > ~/.asoundrc
        echo "ALSA now set to route through CRAS."
        ;;
    "jack")
        echo "Stop CRAS:"
        sudo stop cras
        DEVICE=$DEFAULT_DEVICE
        if ! [ -z "$2" ]; then
            DEVICE="$2"
        fi
        echo "${JACK/_DEVICE_/$DEVICE}" > ~/.asoundrc
        echo "ALSA now set to route through JACK."
        echo "ALSA controls set to $DEVICE"
        ;;
    "help") help;;
    *) help;;
esac

#TODO check if cras is running before unecessarily killing/starting it.
