#!/bin/bash

SYNC_DIR='/media/removable/sd/my shit'

if [ ! -d "$SYNC_DIR" ]; then
    echo "Error! $SYNC_DIR not found!" 1>&2
    exit 1
fi


sync () {
    rsync --delete --exclude "*/node_modules/" -avP "$1" "$SYNC_DIR"/
}

sync $HOME/code
sync $HOME/text
sync $HOME/visual
sync $HOME/aural
