#!/bin/bash

# pushes dotfiles to github

DIR=$HOME/code/projects/dotfiles

cd $DIR

git submodule foreach --recursive add -A --no-ignore-removal
git add -A --no-ignore-removal
git commit -m 'updated dotfiles'
git push



