#!/bin/bash

# pushes changes of dotfiles to github

DIR=$HOME/code/projects/dotfiles

cd $DIR

git submodule foreach --recursive 'git add -A --no-ignore-removal'
git submodule foreach --recursive 'git commit -m "updated dotfiles"'
git submodule foreach --recursive 'git push'

git add -A --no-ignore-removal
git commit -m 'updated dotfiles'
git push



