#!/bin/bash

# pushes changes of dotfiles to github

DIR=$HOME/code/projects/dotfiles

cd $DIR

git submodule foreach 'git add -A --no-ignore-removal && git commit -m "updated dotfiles" && git push'

git add -A --no-ignore-removal
git commit -m 'updated dotfiles'
git push



